import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { HomePage } from '../src/component/home/home.page'
import { Header } from '../src/component/header/header'
import Footer from '../src/component/footer/footer'

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data}/>
    </div>
  )
}

//server rendered
export async function getServerSideProps() {
 const {events_categories} = await import('../data/data.json')
  return {
    props: {
      data: events_categories
    }
  }
}
